### ISSUE TITLE
Numba: 'IndexedArrayType' object has no attribute 'arraytype'

### ISSUE THREAD

**Issue by raymondEhlers** [scikit-hep/awkward-1.0#1158]
### Version of Awkward Array

1.5.1

### Description and code to reproduce

I'm trying to iterate over a record in numba with awkward + vector using the simplified function below (reproducer is below). However, the numba compilation fails with:

```
Traceback (most recent call last):
  File "/software/rehlers/dev/mammoth/projects/exploration/repro_numba.py", line 28, in <module>
    reproducer()
  File "/software/rehlers/dev/mammoth/projects/exploration/repro_numba.py", line 25, in reproducer
    repro(generator_like_jet_constituents=a.constituents)
  File "/software/rehlers/dev/mammoth/.venv/lib/python3.9/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/software/rehlers/dev/mammoth/.venv/lib/python3.9/site-packages/numba/core/dispatcher.py", line 361, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.IntrinsicCallConstraint object at 0x7fd2e2a61ee0>.
'IndexedArrayType' object has no attribute 'arraytype'
During: typing of intrinsic-call at /software/rehlers/dev/mammoth/projects/exploration/repro_numba.py (19)
Enable logging at debug level for details.

File "repro_numba.py", line 19:
def repro(
    <source elided>
        s = 0
        for generator_like_constituent in generator_like_constituents:
        ^
```

(first reported on gitter because I was having some trouble pickling up the array)

It can reproduced with the [this pkl](https://cernbox.cern.ch/index.php/s/rZsnLtwtWoFPniA) and using the code below:

```python
import pickle

import awkward as ak
import numba as nb


@nb.njit  # type: ignore
def repro(
    generator_like_jet_constituents: ak.Array,
) -> None:
    for i, generator_like_constituents in enumerate(generator_like_jet_constituents):
        s = 0
        for generator_like_constituent in generator_like_constituents:
            s += generator_like_constituent.pt

def reproducer() -> None:
    with open("repro.pkl", "rb") as f:
        a = ak.from_buffers(*pickle.load(f))
    repro(generator_like_jet_constituents=a.constituents)

if __name__ == "__main__":
    reproducer()
```

Note that the pickle contains some Momentum4D vectors. I'm not yet sure if I've found a bug or am overlooking something, but I suspect it has something to do with the layout. Thanks!

**Comment by raymondEhlers** [comment]
For future reference, I worked around this by calling `ak.packed` on the arrays that I was passing into my numba function, which based on the info from Jim is what is done for pickle, and it seems to workaround the issue. I suspect this has some costs in terms of performance, but it seems fine for me at the moment
